# This workflow is under construction.
# See https://github.com/mackerelio/docker-mackerel-agent/pull/5
name: Build
on:
  # push:
  #   tags:
  #     - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get tag
        id: get_tag
        # run: echo "::set-output name=tag::${GITHUB_REF##*/}"
        run: echo "::set-output name=tag::x.y.z"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          # push: true
          tags: |
            mackerel/mackerel-agent:latest
            mackerel/mackerel-agent:${{ steps.get_tag.outputs.tag }}
