name: Build
on:
  workflow_call:
    inputs:
      needs-push:
        type: boolean
        default: false
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: inputs.needs-push
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS Credentials
        if: inputs.needs-push
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: "mackere-agent-${{ github.run_id }}-${{ github.run_number }}"
          aws-region: ap-northeast-1
      - name: Login to Public ECR
        if: inputs.needs-push
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: public.ecr.aws
        env:
          AWS_REGION: us-east-1

      - name: Login to GHCR
        if: inputs.needs-push
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: get_tag
        run: echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
      - name: Build (and push if necessary)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ inputs.needs-push }}
          tags: |
            mackerel/mackerel-agent:latest
            mackerel/mackerel-agent:${{ steps.get_tag.outputs.tag }}
            public.ecr.aws/mackerel/mackerel-agent:latest
            public.ecr.aws/mackerel/mackerel-agent:${{ steps.get_tag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/mackerel-agent:latest
            ghcr.io/${{ github.repository_owner }}/mackerel-agent:${{ steps.get_tag.outputs.tag }}
